# Generated by Django 4.2.24 on 2025-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
