# Generated by Django 4.2.24 on 2025-09-25 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_alter_orgmember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
